# Generated by Django 4.0.1 on 2022-03-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_post_categories_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authors',
            field=models.ForeignKey(default='Dima', on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Автор'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
